name: covidreams
dependencies:
  - ipython                   # development
  - conda-forge::tqdm         # progress bar
  - numpy                     # data analysis
  - pandas                    # data analysis
  - scipy                     # data analysis
  - statsmodels               # data analysis - statistics
  - conda-forge::pingouin     # data analysis - statistics
  - matplotlib                # data visualization
  - seaborn                   # data visualization
  - conda-forge::colorcet     # data visualization - colormaps
  - conda-forge::svgutils     # data visualization - figure composition
  - conda-forge::cairosvg     # data visualization - figure composition
  - pip
  - pip:
    - psaw                    # data collection - Reddit API